baseURL = 'https://gwannuu.github.io/'
languageCode = 'en-us'
title = 'Gwannuu blog'
theme = ['PaperMod']

[markup]
    defaultMarkdownHandler = "goldmark"
#   [markup.goldmark]
#     [markup.goldmark.extensions]
#       [markup.goldmark.extensions.passthrough]
#         enable = true
#         [markup.goldmark.extensions.passthrough.delimiters]
#           block = [['\[', '\]'], ['$$', '$$']]
#           inline = [['\(', '\)'], ['$', '$']]



[params]
    math = true
    bibliography = "data/citations/bibliography.bib"

[security.exec]
allow = [
    '^pandoc$'
]
