baseURL = 'https://gwannuu.github.io/'
languageCode = 'en-us'
title = 'Gwannuu blog'
theme = ['PaperMod']

[markup]
  defaultMarkdownHandler = "goldmark"
#   [markup.goldmark]
#     [markup.goldmark.extensions]
#       [markup.goldmark.extensions.passthrough]
#         enable = true
#         [markup.goldmark.extensions.passthrough.delimiters]
#           block = [['\[', '\]'], ['$$', '$$']]
#           inline = [['\(', '\)'], ['$', '$']]

  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true


[params]
    math = true
    bibliography = "data/citations/bibliography.bib"

[security.exec]
allow = [
    '^pandoc$'
]

[caches]  
  [caches.images]
    dir = ':cacheDir/images'


[menu]
  [[menu.main]]
    identifier = "papers"
    name = "Papers"
    url = "/papers/"
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"